### ISSUE TITLE
Refactor Index.php

### ISSUE THREAD

**Issue by bxprdr35** [CIS101-PaceU/infrastructure#18]
Right now the body tag opens in header.php but closes in footer.php. 

Is it best practice to ensure that a tag opens and closes within the same .php file?

**Comment by vjrene** [comment]
We'll talk about it at the meeting but I think it's because the index and other subsequent pages would be including the header (for navigation) and footer. This is to avoid repeating code across multiple files. The pages would still compile because the tags are correctly opening and closing once the page is built. I'm not sure if that makes sense?
