### ISSUE TITLE
Database Synching

### ISSUE THREAD

**Issue by bxprdr35** [CIS101-PaceU/infrastructure#19]
How do we keep our database in synch?  Can this be handled by GIT or do we need to host the database centrally?

What is the cost for hosting centrally?

**Comment by vjrene** [comment]
I think we spoke about this in class, but because we're using mysql on each of our local devices and not on a server, the only real way to keep everything up to date is to settle on a DB with dummy data for now and put the file online (github, email, etc) and just manually update the data as we may alter it.

For future use, this [Stack Overflow](http://stackoverflow.com/questions/17139197/how-to-keep-two-mysql-databases-in-sync) post has a couple of resources we can investigate, including [MySQL Workbench](https://dev.mysql.com/doc/workbench/en/wb-database-synchronization.html) or [Database Sync](https://wordpress.org/plugins/database-sync/) from Wordpress.

Let's discuss at the meeting.
